steps:
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: GET_SECRETS
  #   entrypoint: 'bash'
  #   args:
  #     [
  #       '-c',
  #       'gcloud secrets versions access latest --secret=env > .env',
  #     ]
  
  - name: docker
    id: Build 
    # waitFor:
    #   - GET_SECRETS
    dir: api
    args: ['build', '--tag', '${_REGISTRY}/$PROJECT_ID/${_BUILD_TARGET}/${_BUILD_TARGET}-${_VERSION}', '.']

  - name: docker
    id: Push 
    waitFor:
      - Build 
    args: ['push', '${_REGISTRY}/$PROJECT_ID/${_BUILD_TARGET}/${_BUILD_TARGET}-${_VERSION}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    waitFor:
      - Push 
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_CLOUD_RUN}streamlit-${_VERSION}'
      - '--image'
      - '${_REGISTRY}/$PROJECT_ID/${_BUILD_TARGET}/${_BUILD_TARGET}-${_VERSION}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--timeout=3600'
      - '--memory=4Gi'
      - '--cpu=4'
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'
      - '--concurrency=10'
      - '--max-instances=2'
      - '--session-affinity'
      - '--add-cloudsql-instances=${_CLOUD_SQL}'
      # - '--set-env-vars'
      # - 'STREAMLIT_SERVER_ADDRESS=0.0.0.0,STREAMLIT_SERVER_PORT=8080,DATABASE_URL=${_POSTGRES_CONN}${_CLOUD_SQL}'
      # - '--update-secrets'
      # - 'ALGOLIA_API_KEY=ALGOLIA_API_KEY:latest'

substitutions:
  _BUILD_TARGET: {name}-api
  _CLOUD_RUN: {name}-
  _REGION: us-east1
  _REGISTRY: us-east1-docker.pkg.dev
  # _CLOUD_SQL: 
  # _POSTGRES_CONN: postgresql+psycopg://{un}:{pw}@/{db}?host=/cloudsql/
  # _LANGCHAIN_TRACING_V2: 'false'

images:
  - '${_REGISTRY}/$PROJECT_ID/${_BUILD_TARGET}/${_BUILD_TARGET}' 
  # - '${_REGISTRY}/$PROJECT_ID/${_BUILD_TARGET}/${_BUILD_TARGET}-${_VERSION}' 
